bitrise-steplib/steps-deploy-to-bitrise-io

main.go, step.yml
To support workflows where multiple artifacts have an install page, I've had this step export two new environment variables that contain all public URLs, instead of just the last one. The URLs are accessible through:
* a pipe-separated array of URLs, `BITRISE_PUBLIC_INSTALL_PAGE_URL_LIST`
* a map of files and URLS, `BITRISE_PUBLIC_INSTALL_PAGE_URL_MAP.` Entries are separated by pipes (|), keys and values a colon (:)
This fixes #43 and #22
=> Export all public URLs to the environment

step.yml
Fixes https://github.com/bitrise-io/steps-deploy-to-bitrise-io/issues/57
Now that we have Organizations and Org Groups it's misleading to call app team roles as Groups IMO. More details: https://github.com/bitrise-io/steps-deploy-to-bitrise-io/issues/57
=> Rename Notify User Group to Notify User Roles

main.go, uploaders/utils.go
Originally the bug was:
"The `BITRISE_PUBLIC_INSTALL_PAGE_URL_MAP` variable contains the `.aab` file's name with the generated `universal.apk`'s Public Install Page"
---
But as the AAB artifact does not have a public install page I removed it from the `BITRISE_PUBLIC_INSTALL_PAGE_URL_MAP` as well.
=> Tool 1017 fix aab public install page

bundletool/bundletool.go
Customer is asking for bundletool to be upgraded because of a bug (more details here: https://github.com/google/bundletool/issues/113) preventing users from bundling the universal APKs from .aab.
This was fixed in version 0.10.3 but 0.12.0 is out, I am requesting upgrading from 0.9.0 to 0.12.0.
#114
=> Change bundletool version to 0.12.0

bundletool/bundletool.go
After upgrading from Android Gradle Plugin 3.5.X to 3.6.X, I'm running into the same issue as #114. 
> Error: Program type already present: $r8$backportedMethods$utility$Long$1$hashCode
[BT:0.12.0] Error: Dex merging failed.
Our Bitrise build is already using bundletool 0.12.0. Upgrading to the latest version (currently 0.13.4) resolves the issue. Is it possible to merge this PR to upgrade to that version?
In the mean time I'll fork the repo to triage the issue until bundletool has been upgraded.
=> Change bundletool version to 0.13.4

step.yml
- Requires _PATCH_ [version update](https://semver.org/)
Some links have a broken Markdown syntax, let's fix them.
=> Fix broken links in description

main.go, step.yml
- Requires _MINOR_ [version update](https://semver.org/)
We are going to deprecate the universal APK generation capability of this Step, in favor of the _Export Universal APK_ Step.
As a first step, a deprecation note is added indicating the process for the Customers. We will completely remove the capability with the next major release.
- A deprecation note is added to the description of the input.
- A warning message is added to the deployment logic.
The depreciation is supported by [this](https://bitrise.atlassian.net/wiki/spaces/STEP/pages/1168048427/Investigate+universal+APK+exporting) investigation.
=> Propose the deprecation of universal APK generation

step.yml
- Requires _PATCH_ [version update](https://semver.org/)
=> Fix broken Markdown links

bitrise.yml, test/converters/xcresult/testsummariesplist.go, test/converters/xcresult/xcresult.go, test/converters/xcresult3/action_test_plan_summary.go, test/converters/xcresult3/converter.go, test/junit/xml.go, test/test_test.go, test/testdata/ios_testsummaries_plist.golden, test/testdata/ios_xml_output.golden, vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require.go.tmpl, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/require_forward.go.tmpl, vendor/github.com/stretchr/testify/require/requirements.go, vendor/modules.txt
based ont this ticket: https://bitrise.atlassian.net/browse/BINS-246
For both iOS and Android there are a possibility of skipping specific test cases when testing. Android has a build in junit4 generator thus working fine and sends us the skipped statuses for the test cases.
However for iOS this step converts xcresult file into junit4 but for some reason the skipped status for test cases were completely skipped/forgotten.
This PR is about to convert the skipped status as well.
This should be a patch version bump.
=> [BINS-246] Add skipped field parsing to the xc converter

test/converters/converters_test.go, test/converters/xcresult/testsummariesplist.go, test/converters/xcresult/xcresult.go, test/converters/xcresult3/action_test_plan_summary.go, test/converters/xcresult3/action_test_plan_summary_test.go, test/converters/xcresult3/action_test_summary.go, test/converters/xcresult3/action_test_summary_group.go, test/converters/xcresult3/converter.go, test/converters/xcresult3/converter_test.go
I'd suggest a *MINOR* [version update](https://semver.org/).
There should be no breaking changes, but the logic of how we decide for xcresult3 report if a given test is failed changed.
Previously it was based on whether the code could find a failure for it in the failure summaries, while the new code now depends on the test's `TestStatus.Value == "Failure"`.
That said, there's one semi-breaking-change: the Failure Message in the xcresult3->junit generated report changed. Previously it included a url encoded reference (which is what the "issues" summary has as an error message), while the new solution now constructs the error message itself with the format: `file-path:line-number - error message`. You can see an example of this change here: …
=> [BINS-319] junit report generation fix when report includes a flaky rerun

test/converters/junitxml/junitxml.go, test/converters/junitxml/junitxml_test.go, test/converters/junitxml/testdata/testsuites.junit
Fastlane saves the junit reports with a `.junit` file extension instead of an `.xml`. The content follows the same format, just the file extension has changed.
- The junit converter now can parse the files with `junit` extension.
=> [SWAT-89] Add support for junit file extension

main.go
Fixes #162 (SWAT-816)
The `tar` command can't change the pathname of the files when unarchiving so we need to avoid using the absolute path of the directory. Hence we set the working directory as the parent directory of the directory we're archiving via the `-C` argument when invoking `tar`.
https://docstore.mik.ua/orelly/unix/upt/ch20_10.htm
https://stackoverflow.com/a/3035446
We now execute `tar cf /path/of/output.tar -C /path/of/directory_to_archive/ .`
The `-C` argument makes `tar` switch to the given directory before archiving and we pass `.` in order to denote that all files in that directory should be archived.
Originally tried to just set the working directory of the command, but that led to an extra parent directory when …
=> Avoid using absolute path with tar command when archiving

deployment/collector.go, deployment/collector_test.go, main.go
We discussed that using `zip` for build artifacts and `tar` for pipeline intermediates is not ideal moving forward due to having to maintain both tools across stacks.
Here's the accompanying `pull-pipeline-intermediates` PR: https://github.com/bitrise-steplib/bitrise-step-pull-intermediate-files/pull/3
Reverting the changes from previous releases. Leaving vendored dependencies.
Also considered just compressing pipeline intermediates with the existing changes to `tar`.
Note: `zip` throws an error when zipping empty directories.
Details are here under error code 12: https://linux.die.net/man/1/zip
To work around this for the e2e tests I added a file to the directory.
The plan moving forward is to consolidate and use `zip` across the …
=> Revert to zipping pipeline intermediates

step.yml
Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)
The bundletool used is over 1.5 years old. Meanwhile many improvements have been applied to the tool to support latest android features and packaging.
Updates the bundletool default version. Here a list of release notes: https://github.com/google/bundletool/releases
We have experienced issues while the step was downloading that version of bundletool, failing the build. One step before we downloaded bundletool (latest) and the download was successful. I am aware that bumping version doesnt fix download issues but this is how I realized we were downloading a 1.5yo version.
=> Update bundletool version

androidsignature/signature.go, uploaders/aabuploader.go
The Release Automation team needs to differentiate between signed and unsigned aab files. At the moment such information is not included in the metadata file while the iOS counterpart has. 
The Step extract the cretificate's DN value from aab. The signed aabs always have this while for the unsigned ones it will be empty. It uses the `jarsigner` tool for this which comes as part of the Android SDK.
The change is not covered with unit test because at the moment none of the metadata is tested. We have integration tests to upload the various supported files, unit tests for test result conversions to xml file and extensive tests for the test result handling. It is not clear how the metadata file can be downloaded as it is only used by …
=> [RA-1435] Read aab signature

bitrise.yml, main.go, main_test.go
We discovered that uploading a large amount of assets with the steps takes too long. For example, uploading 1200 images takes approximately 15 minutes. This is because the step performs the upload item by item. Adding concurrency to the file uploads will make the step 8x faster. 
The main change is that we can control the concurrency with the `BITRISE_DEPLOY_UPLOAD_CONCURRENCY` env var. This is needed because we want to experiment with what is ideal value for our systems. If the env var is missing then the step will use a concurrency of 1. Also at the moment we limit the max value to prevent the anything abusing this value. 
The second change is that the previous implementation was uploading the apks first then everything else. Now …
=> Add parallel upload

bundletool/bundletool.go
The jdk has some regression which means 3rd party tools will face an error when working with apk, zip or jar files. The deploy step faces the same issue.
This is already fixed in newer jdk versions but we need time to update the stacks. Until then we need to live with this workaround. The build env team will clean it up once the newer Java versions are deployed.
There is only a single extra parameter in the jar execution which disables the flawed field validation.
=> Disable Zip64 extra field validation

test/converters/xcresult3/action_test_summary.go, test/converters/xcresult3/action_test_summary_group.go, test/converters/xcresult3/converter.go, test/junit/xml.go, test/test_test.go, test/testdata/ios_device_config_xml_output.golden, test/testdata/ios_xml_output.golden, vendor/github.com/bitrise-io/go-utils/v2/command/command.go, vendor/github.com/bitrise-io/go-utils/v2/command/errorcollector.go, vendor/modules.txt
The generated xml data representation is not accurate for retried tests. These test runs appear as separate entries in the xml and we need to apply grouping/filtering logic to consume them. 
A simple logic is to simply use the test class name and test name. This works for the regular use cases but there is a new feature which breaks this which is the device configuration tests. This is a handy new Xcode feature where you can tell Xcode to launch the given tests on all language / orientation / interface mode combinations with:
```
override class var runsForEachTargetApplicationUIConfiguration: Bool {
true
}
```
But tests launched like this will have the same name and identifier and only their configuration will be different. Xcode …
=> [CI-2284] Add configuration hash to the xml data

report/api/models.go, report/collect.go, report/models.go, report/report.go, report/report_test.go
This PR is from @AndrasEszes but he does not have right access so I am creating it temporarily.
We want to differentiate user generated reports from the ones created by our steps so we introduce a metadata file which will contain Bitrise specific information. The step will take the category value from this file if the file exists. The website will render the html in different locations based on this value.
=> [CI-2433] Send test report category

main.go
A few maddening errors containing `%!v(MISSING)` appeared in the logs (likely a go format string was included in the upload URLs). Hopefully found them all, caused by bad printf usage.
```
deploy failed, error:
failed to create file artifact: /[...]/noexisttest%!s(MISSING)%!v(MISSING):
failed to get file size, error: file not exist at: /[...]/noexisttest%!s(MISSING)%!v(MISSING)
```
=> Fix (MISSING) formatting errors due to unescaped printf usages

report/collect.go, report/collect_test.go, report/report_test.go
The uploaded html reports could not load the css and js files because they were upload with an incorrect `text/plain` content type. This PR sets correct content type for them.
=> Set content type for known extensions

main.go, uploaders/fileuploader.go
This PR implements a workaround for deploying generic files, that are potentially being modified during the deployment process.
The workaround is creating a snapshot of generic files at max 1GB file size, by copying them to a tmp path and deploying this tmp file, instead of the original file.
=> Deploy the snapshot of generic files under 1GB file size

report/collect_test.go, test/converters/converters_test.go, test/converters/xcresult3/action_test_summary_group.go, test/converters/xcresult3/converter.go, test/converters/xcresult3/converter_test.go, test/converters/xcresult3/logging.go, test/converters/xcresult3/model3/conversion.go, test/converters/xcresult3/model3/data.go, test/converters/xcresult3/model3/export.go, test/converters/xcresult3/model3/testresults.go, test/converters/xcresult3/xcresult3.go, test/converters/xcresult3/xcresulttool.go, test/testdata/ios_device_config_xml_output.golden
Since Xcode 16 we have a new way to extract test information from the xcresult file with xcresulttool. This PR removes the legacy flag and updates the step to use the new method. 
The new method uses a completely different data structure and cannot be easily fit into the old one. So there are a new set data models and the whole method is separated from the old one.
=> [CI-4420] New test result extraction

main.go, step.yml, test/converters/converters.go, test/converters/junitxml/junitxml.go, test/converters/xcresult/xcresult.go, test/converters/xcresult3/converter.go, test/test.go, test/test_test.go
Some customers xcresult file might not be compatible with the new parsing (or there is a bug in the extraction tool) and this new input can force the step to use the legacy extraction method.
=> [CI-4808] Legacy xcresult parsing input

test/converters/xcresult3/converter.go, test/converters/xcresult3/converter_test.go, test/converters/xcresult3/model3/conversion.go, test/converters/xcresult3/model3/conversion_test.go, test/converters/xcresult3/model3/data.go, test/testdata/ios_device_config_xml_output.golden
Currently the test result converter isn't handling test case retries for Xcode test results. Only the summary test case is added to the internal test report model, actual test case reruns are not parsed.
This PR updates the Xcode test result parser to parse test case retries and add the reties as separate test cases to the converted test report, the summary test case is not part of the converted report anymore.
This xcresult:
```
"children" : [
{
"children" : [
{
"name" : "DarkAndLightModeTests.swift:25: failed - Reached 1",
"nodeType" : "Failure Message",
"result" : "Failed"
}
],
"duration" : "0,11s",
"durationInSeconds" : 0.11242496967315674,
"name" : "Retry 1",
"nodeIdentifier" : "1",
"nodeType" : "Repetition",
"result" : …
```
=> Xcresult retry test cases
